#include "buttons.h"                                                                                    // Library for be able to use irq library

void button_init(void) {

    // Activate the GPIOC clock and set the SYSCFG bit for be able to use the GPIO pins as interruption sources and set up them (Turn on the SYSCFG clock)
    RCC->AHB2ENR |= RCC_AHB2ENR_GPIOCEN;
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

    // Define pin 13 of port C as INPUT
    GPIOC->MODER &= ~GPIO_MODER_MODE13; 

    // Define PC13 as source of EXTI3 extern interruption
    SYSCFG->EXTICR[3] &= ~SYSCFG_EXTICR4_EXTI13;                                                        // Clean the register for let it ready to set up                                              
    SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI13_PC;                                                      // Select the pin PC13 as the extern interruption for the EXTI3 source
    
    // Set up EXTI to configure the interruption source
    EXTI->IMR1  |= EXTI_IMR1_IM13;                                                                      // Interrupt Request from line 13 is not masked (The interruption is on, enable the interruption)
    EXTI->RTSR1 &= ~EXTI_RTSR1_RT13;                                                                    // Rising trigger disabled
    EXTI->FTSR1 |= EXTI_FTSR1_FT13;                                                                     // Falling trigger enabled

    // Configure the corresponding interruption in NVIC (Nested Vector Interrupt Controller). The microcontroller will be able to handle the interruption generated by EXTI
    NVIC_EnableIRQ(EXTI15_10_IRQn);                                                                     // EXTI Line[15:10] interrupts
}

void EXTI15_10_IRQHandler(){
    
    __disable_irq();
    switch_LED_g();                                                                                     // Switch the green LED
    // Clean the interupt flag related with PC13
    EXTI->PR1 |= EXTI_PR1_PIF13;                                                                        // Bit set when a interruption arrives, and is cleared by writting a '1' to the bit
    __enable_irq();
}
